### ISSUE TITLE
Bash completion files installed in directory different from docs?

### ISSUE THREAD

**Issue by peter-jansson** [apptainer/apptainer-admindocs#43]
## Which Document page:

[installation.rst](https://github.com/apptainer/apptainer-admindocs/blob/b90b33e2f6fbda29c1b64b6da8985d860ebf092f/installation.rst#source-bash-completion-file)

### Expected results:

Bash completion files installed according to the document page.

### Actual results:

The code [here](https://github.com/apptainer/apptainer/blob/39d336c8d5bf045af030665d4b5055c02f57ef33/mlocal/frags/build_cli.mk#L55) seem to indicate they are installed elsewhere.

**Comment by DrDaveD** [comment]
You're correct.  The path changed and the documentation didn't get updated.  Could you please submit a PR?  Please note the [apptainer CONTRIBUTING guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), especially the part about the Developer Certificate of Origin.
